[package]
name = "sudoku-app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
instant = { version = "0.1.12", features = ["wasm-bindgen", "inaccurate"] }
seed = "0.9.2"

sudoku = { git = "https://github.com/taotao54321/sudoku.git", version = "0.1.0" }
